/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "app-manage": () => import("@/views/app-manage/index.vue"),
  "app-url-manage": () => import("@/views/app-url-manage/index.vue"),
  "app-version-manage": () => import("@/views/app-version-manage/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "redirect-url": () => import("@/views/redirect-url/index.vue"),
  "region-blacklist": () => import("@/views/region-blacklist/index.vue"),
  "region-whitelist": () => import("@/views/region-whitelist/index.vue"),
  "url-handle-log": () => import("@/views/url-handle-log/index.vue"),
};
