/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'app-manage',
    path: '/app-manage',
    component: 'layout.base$view.app-manage',
    meta: {
      order: 2,
      title: 'app-manage',
      i18nKey: 'route.app-manage',
      icon: 'mdi:apps'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      order: 1,
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'redirect-url',
    path: '/redirect-url',
    component: 'layout.base$view.redirect-url',
    meta: {
      order: 3,
      title: 'redirect-url',
      i18nKey: 'route.redirect-url',
      icon: 'mdi:curling'
    }
  },
  {
    name: 'region-blacklist',
    path: '/region-blacklist',
    component: 'layout.base$view.region-blacklist',
    meta: {
      order: 4,
      title: 'region-blacklist',
      i18nKey: 'route.region-blacklist',
      icon: 'mdi:file-document-minus'
    }
  },
  {
    name: 'region-whitelist',
    path: '/region-whitelist',
    component: 'layout.base$view.region-whitelist',
    meta: {
      order: 4,
      title: 'region-whitelist',
      i18nKey: 'route.region-whitelist',
      icon: 'mdi:file-document-check'
    }
  }
];
